#!/usr/bin/perl
# OmySEX_test_v3.pl
# by Nate 
# Sex fish by GTseq
# This version of the script uses information from the version 2 genotyping output as a control for the sex marker.
# It then generates a genotypic sex and appends the sex marker to the end of the .genos file.
# The sex marker is then included in the summary file generated by the GTseq_GenoCompile_v2.pl script.
# update 5/2016: Incorporates fuzzy match to male specific probe allowing for a single base difference in probe.  Makes
# sex marker data compatible with GTseq_ErrorReport.pl script.

use strict; use warnings;
use String::Approx 'amatch';

my @Files = `ls *.fastq`;
chomp ( @Files );

foreach my $samples (@Files){
	open (FILE, "<$samples") or die;
	$samples =~ s/.fastq//;
	my $genos = "$samples.genos";
	my $OT_reads = 0;
	my $primer_counts = 0;
	my $primerOT = 0;
	my $perofallOTreads = 0;
	open (READ, "<$genos") or die;
		while (<READ>) {
			if ($. == 1) {
				my @info = split ",", $_;
				my @info2 = split ":", $info[2];
				$OT_reads = $info2[1];
					}
				}
	close READ;
	open (OUT, '>>', $genos) or die "Error opening $genos\n";
	my $counts = 0;
	my $cntrl_counts = 0;
	my $sex_geno = "00";
	my $geno_class = "NA";
	while (<FILE>) {
		chomp;
		my $info_line = $_;
		my $seq_line = <FILE>;
		my $info_line2 = <FILE>;
		my $qual_line = <FILE>;
		if($seq_line =~ m/^GCGCATTTGTATGGTGAAAA/) {$primer_counts++}
		if(($seq_line =~ m/^GCGCATTTGTATGGTGAAAA/) && (amatch("ATGTGTTCATATGCCAG", ["S1"], $seq_line))) {$counts++}
	}
	if($primer_counts == 0) {$primer_counts = 1}
	$primerOT = $counts/$primer_counts*100;
	$primerOT = sprintf("%.3f", $primerOT);
	$perofallOTreads = $counts/$OT_reads*100;
	$perofallOTreads = sprintf("%.3f", $perofallOTreads);
	$cntrl_counts = $OT_reads * 0.001;
	$cntrl_counts = int ( $cntrl_counts );
	if ($cntrl_counts == 0) {$cntrl_counts = 1}
	if ($counts == 0) {$counts = 1}
	my $ratio = $cntrl_counts/$counts;
	$ratio = sprintf("%.3f", $ratio);
	if ($cntrl_counts + $counts < 10) {$sex_geno = "00", $geno_class = "NA"}
	elsif ($ratio >= 10) {$sex_geno = "XX", $geno_class = "A1HOM"}
	elsif ($ratio <= 0.1) {$sex_geno = "XY", $geno_class = "A2HOM"}
	elsif ($ratio <= 0.2) {$sex_geno = "00", $geno_class = "NA"}
	elsif ($ratio <= 5) {$sex_geno = "XY", $geno_class = "HET"}
	
	print OUT "OmyY1_2SEXY,X=$cntrl_counts,Y=$counts,$ratio,$sex_geno,$geno_class,0,0,$counts,$primerOT,$perofallOTreads,Pass,0\n";
close FILE;
close OUT;
}

